version: '3.7'

x-environment: &default-env
  DEBUG: 'true'
  DJANGO_SECRET_KEY: 'w*%2ld*&(-jp0cuukvd&s(c%m3i!fzcgt1edw6g-34q5_ji5m'
  SQL_HOST: 'db'
  SQL_PORT: '5432'
  WAIT_FOR_POSTGRES: 'true'
  DATABASE_URL: 'postgres://postgres:postgres@db/postgres'
  REDIS_LAYER: 'true'
  REDIS_HOST: 'redis'
  REDIS_PORT: '6379'

services:
  redis:
    image: redis:5.0.5-alpine
    volumes:
      - ./target/redis:/data
    restart: always
  webapp:
    build:
      context: ./clowdflows-webapp/.
      target: dev
    command: >
        sh -c "npm run start"
    ports:
      - 127.0.0.1:8080:8080/tcp
    volumes:
      - ./clowdflows-webapp/src:/app/src
  backend:
    build:
      context: ./clowdflows-backend/.
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      <<: *default-env
      MIGRATE: 'true'
      COLLECTSTATIC: 'true'
    ports:
      - 127.0.0.1:8000:8000/tcp
    volumes:
      - ./clowdflows-backend:/usr/src/app
#     - ./packages:/usr/src/app/packages
  db:
    image: postgres:10.5-alpine
    restart: always
    volumes:
      - ./target/postgres_data:/var/lib/postgresql/data

